title: ewen
description: Ewen's home page on the World Wide Web.
url: https://ewen.io
permalink: /posts/:title
timezone: Europe/London
kramdown:
  hard_wrap: true
sass:
  sass_dir: assets
  style: compressed
collections:
  sounds:
    output: true
  notes:
    output: true
  pages:
    output: true
  reading:
    output: true
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
